#!/bin/bash
# Create generic prettier config file

# exit script if error or try to use undeclared variable
set -o errexit -o nounset

FILENAME=.prettierrc

if [ -f $FILENAME ]; then
  echo "You already have a $FILENAME file"
  exit 0
fi

# create prettier file
touch $FILENAME

# insert most used settings into newly created .prettierrc file
cat >> $FILENAME <<'EOF'
{
  "arrowParens": "always",
  "bracketSpacing": false,
  "printWidth": 80,
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false
}
EOF

exit 0
