#!/usr/bin/env bash

session=$(find ~/projects ~/courses ~/Documents/docs -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

# create new detached tmux session if no session with same name already created
if ! tmux has-session -t "$session_name" 2> /dev/null; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

# switch to newly created session
tmux switch-client -t "$session_name"
